### ISSUE TITLE
manage multiple gmail accounts 

### ISSUE THREAD

**Issue by kiquenet** [kpstolk/Gmail-Api#1]
IMHO, very helpful Gmail Client, I think. I'll tested deep.

But I have one question, how could I manage multiple gmail accounts in my Console, Windows Forms, WPF or UWP application ?

**Comment by octocat-mona** [comment]
You could reuse the `ServiceAccountCredential` and link Gmail accounts you want to access to the `ClientEmail`s Gmail account. Requires that you add a Google OAuth project with the scopes you need and accept the consent screen once per Gmail account manually. I think this is the easiest way but a little more complicated.

Second alternative would be to store the `ServiceAccountCredential` per Gmail account and use the same email address for the `ClientEmail` property and `emailAddress` param in the `GmailClient` constructor. In this case you would have a `GmailClient` instance per Gmail account.

Does this help?
