### ISSUE TITLE
Last version is not in NuGet

### ISSUE THREAD

**Issue by marinaqa** [kpstolk/Gmail-Api#2]
NuGet package contains KP.GmailApi, but last build is named KP.GmailClient and has extended options. Could you please upload GmailClient  to NuGets?

**Comment by octocat-mona** [comment]
I'll investigate it, the current [KP.GmailApi](https://www.nuget.org/packages/KP.GmailApi/) can't be renamed so will have to create a new NuGet package.

**Comment by octocat-mona** [comment]
It's now available on [NuGet.org](https://www.nuget.org/packages/KP.GmailClient/)

**Comment by marinaqa** [comment]
Thank you!

**Comment by marinaqa** [comment]
I see that new NUGet package works only with .Net Standard, but I would also expect build for .Net Framework 4.5.2. Thanks
