### ISSUE TITLE
KP.GmailClient NuGet pakage is build only for .Net Standart

### ISSUE THREAD

**Issue by marinaqa** [kpstolk/Gmail-Api#3]
I see that new NUGet package works only with .Net Standard, but I would also expect build for .Net Framework 4.5.2. Thanks

**Comment by octocat-mona** [comment]
Hi, sorry for the delayed response, I've added support for .NET 4.5 in the next version.

**Comment by octocat-mona** [comment]
Version 2.0.1 is now available [on NuGet](https://www.nuget.org/packages/KP.GmailClient/2.0.1.188).
