### ISSUE TITLE
SendAync does not take 4 arguments

### ISSUE THREAD

**Issue by muzzammilhussain** [kpstolk/Gmail-Api#4]
sentMessage = await client.Messages.SendAsync(emailAddress, "The subject", "<h1>HTML body</h1>", isBodyHtml: true);

This is giving me error that SendAsyc does not take 4 arguments. It just taking 2

**Comment by octocat-mona** [comment]
Does it give you a compile error?
Because [`SendAsync`](https://github.com/kpstolk/KP.GmailClient/blob/master/src/KP.GmailClient.Tests/Playground.cs#L44) should just work with those 4 parameters.

**Comment by muzzammilhussain** [comment]
Yes as soon as I give 4 parameters. It says SendAsyc does not take 4 parameters. Do i Send code sample?

**Comment by octocat-mona** [comment]
I think I found what your issue is, did you add this `using` line?
```csharp
using KP.GmailClient.Services.Extensions;
```

**Comment by octocat-mona** [comment]
@muzzammilhussain Did this solve your issue?
