### ISSUE TITLE
FileStore breaking token.

### ISSUE THREAD

**Issue by StoyanYonkov** [kpstolk/Gmail-Api#6]
Hello, I found an issue where if the newly received token is shorter in lenght than the currently saved one it will break the token. As the token is being saved with File.OpenRead it is a stream and once JSON writes the new token to the stream if its shorter there will be left out text after the new token esentially making it an invalid JSON file and causing emails to no longer be sent. 

Here is how i fixed it i am not sure if this is the best way to do so.

        public async Task StoreTokenAsync(OAuth2Token token)
        {
            // Only write to disk when one of the 2 tokens changed
            if (_cachedToken != null && _cachedToken.AccessToken == token.AccessToken && _cachedToken.RefreshToken == token.RefreshToken)
            {
                return;
            }
           
            File.WriteAllText(_tokenFile, string.Empty);  //Fix for token breaking !!!!!!
            using (var stream = File.OpenWrite(_tokenFile))
            {
                await JsonSerializer.SerializeAsync(stream, token);
            }
            _cachedToken = token;
        }

**Comment by octocat-mona** [comment]
Hi, sorry for the delay in response.

I did some tests and indeed a malformed token is sometimes written to disk.
A new version of `System.Text.Json` package does seem to fix this issue.
